app/models/post.py
from app import db
from datetime import datetime


class Post(db.Model):

    __tablename__ = 'posts'

    id = db.Column(db.Integer, primary_key=True)
    timestamp = db.Column(db.DateTime, default=datetime.utcnow)
    text = db.Column(db.String(255))
    user_id = db.Column(db.Integer, db.ForeignKey('users.id'))
    subreddit_id = db.Column(db.Integer, db.ForeignKey('subreddits.id'))

    def __repr__(self):
        return '<Subreddit {}>'.format(self.id)

app/models/subreddit.py
from app import db
# from flask import current_app
from datetime import datetime


class Subreddit(db.Model):

    __tablename__ = "subreddits"

    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String(60), unique=True)
    date_created = db.Column(db.DateTime, index=True, default=datetime.utcnow)
    description = db.Column(db.String(255))
    user_id = db.Column(db.Integer, db.ForeignKey('users.id'))
    posts = db.relationship('Post', backref='subreddit', lazy='dynamic')

    def __repr__(self):
        return '<Subreddit {}>'.format(self.name)

app/models/user.py
from app import db
from flask import current_app
from werkzeug.security import generate_password_hash, check_password_hash
from app import login_manager
from flask_login import UserMixin
from time import time
import jwt


@login_manager.user_loader
def load_user(user_id):
    return User.query.filter_by(id=user_id).first()


subs = db.Table('subs',
                db.Column('user_id', db.Integer, db.ForeignKey('users.id')),
                db.Column('subreddit_id', db.Integer,
                          db.ForeignKey('subreddits.id')))


class User(UserMixin, db.Model):
    __tablename__ = "users"

    id = db.Column(db.Integer, primary_key=True)
    email = db.Column(db.String(120), unique=True)
    password_hash = db.Column(db.String(128))
    username = db.Column(db.String(50), unique=True)

    subscriptions = db.relationship(
        'Subreddit', secondary=subs,
        backref=db.backref('subscribers', lazy='dynamic'),
        lazy='dynamic')

    my_subreddits = db.relationship('Subreddit', backref='creator',
                                    lazy='dynamic')

    posts = db.relationship('Post', backref='author', lazy='dynamic')

    def __init__(self, email, username):
        self.email = email
        self.username = username

    def get_reset_password_token(self, expires_in=600):
        return jwt.encode(
            {
                'reset_password': self.id,
                'exp': time() + expires_in
            },
            current_app.config['SECRET_KEY'],
            algorithm='HS256').decode('utf-8')

    @staticmethod
    def verify_reset_password_token(token):
        try:
            id = jwt.decode(token, current_app.config['SECRET_KEY'],
                            algorithms=['HS256'])['reset_password']
        except Exception:
            return
        return User.query.get(id)

    def set_password(self, raw_password):
        self.password_hash = generate_password_hash(raw_password)

    def check_password(self, raw_password):
        return check_password_hash(self.password_hash, raw_password)

    def __repr__(self):
        return '<User %r>' % (self.username)

app/subreddit/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, TextAreaField
from wtforms.validators import DataRequired, Length,\
    ValidationError

from app.models.subreddit import Subreddit


class CreateCommunityForm(FlaskForm):
    name = StringField('Username', validators=[DataRequired()])
    description = TextAreaField('Description', validators=[
        DataRequired()])

    def validate_name(self, name):
        sub = Subreddit.query.filter_by(name=name.data).first()
        if sub is not None:
            raise ValidationError('A subreddit with this name already exists')


class PostForm(FlaskForm):
    post_text = TextAreaField('Post', validators=[
        DataRequired(),
        Length(min=1, max=200)
    ])

app/__init__.py
from flask import Flask
from flask_sqlalchemy import SQLAlchemy
from flask_migrate import Migrate
from flask_login import LoginManager
from flask_mail import Mail
from flask_scss import Scss

from config import Config

db = SQLAlchemy()
migrate = Migrate()
login_manager = LoginManager()
login_manager.login_view = 'auth.login'
mail = Mail()


def create_app(config_class=Config):
    app = Flask(__name__)
    app.config.from_object(config_class)
    db.init_app(app=app)
    migrate.init_app(app=app, db=db)
    login_manager.init_app(app=app)
    mail.init_app(app=app)
    Scss(app)
    from app.auth import auth as auth_bp
    app.register_blueprint(auth_bp)
    from app.core import core as core_bp
    app.register_blueprint(core_bp)
    from app.subreddit import subreddit as subreddit_bp
    app.register_blueprint(subreddit_bp)

    return app

app/core/__init__.py
from flask import Blueprint

core = Blueprint('core', __name__)

from app.core import views

app/core/views.py
from flask import render_template
from app.models.user import User
from app.models.subreddit import Subreddit
# from flask_login import login_required
from app.core import core


@core.route('/', methods=['GET', 'POST'])
def index():
    users = User.query.all()
    subreddits = Subreddit.query.all()
    return render_template('core/index.html', users=users,
                           subreddits=subreddits)

app/subreddit/__init__.py
from flask import Blueprint

subreddit = Blueprint('subreddit', __name__)

from app.subreddit import views

app/subreddit/views.py
from flask import render_template, url_for, redirect
from flask_login import current_user, login_required

from app import db
from app.models.subreddit import Subreddit
from app.models.post import Post
from app.subreddit import subreddit
from .forms import CreateCommunityForm, PostForm


@login_required
@subreddit.route('/subreddit/create', methods=['GET', 'POST'])
def create():
    form = CreateCommunityForm()
    if form.validate_on_submit():
        new_sub = Subreddit(name=form.name.data,
                            description=form.description.data,
                            creator=current_user)
        db.session.add(new_sub)
        db.session.commit()
        return redirect(url_for('core.index'))
    return render_template('subreddit/create.html', form=form)


@login_required
@subreddit.route('/r/<name>', methods=['GET', 'POST'])
def subreddit(name):
    subreddit = Subreddit.query.filter_by(name=name).first_or_404()
    form = PostForm()
    if form.validate_on_submit():
        new_post = Post(text=form.post_text.data, author=current_user,
                        subreddit=subreddit)
        db.session.add(new_post)
        db.session.commit()
        return redirect(url_for('subreddit.subreddit', name=name))
    posts = Post.query.filter_by(subreddit=subreddit)
    return render_template('subreddit/subreddit.html',
                           subreddit=subreddit,
                           form=form,
                           posts=posts)

app/templates/_formhelper.html
{% macro render_field(field) %}
<div class="form-group">
  
  {% if field.type == 'BooleanField' %}
    {{ field.label }}
  {% endif %}

  {{ field(**kwargs)|safe }}
  {% if field.errors %}
  {% for error in field.errors %}
  <small id="" class="form-text text-danger">{{ error }}</small>
  {% endfor %}
  {% endif %}
</div>

{% endmacro %}

app/templates/base.html
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Flask App</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='css/core.css') }}">
</head>

<body>
        <!-- <nav class="navbar sticky-top navbar-light bg-light">
            <a class="navbar-brand" href="#">Sticky top</a>
        </nav> -->
    
    <div class="container-fluid">
        {% block content %}
        {% endblock %}
    </div>
        


<!-- JS, Popper.js, and jQuery -->
<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js" integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI" crossorigin="anonymous"></script>

</body>

</html>

app/templates/core/index.html
{% extends 'base.html' %}

{% block content %}
<a href="{{ url_for('auth.logout') }}">logout</a>
<a href="{{ url_for('subreddit.create') }}">Create community</a>
<h3>Users</h3>
<ul>
    {% for user in users%}
    <li>{{ user.username }}</li>
    {% endfor %}
</ul>
<h3>subreddits</h3>
<ul>
    {% for sub in subreddits%}
    <li><a href="{{ url_for('subreddit.subreddit', name=sub.name )}}">r/{{ sub.name }}</a></li>
    {% endfor %}
</ul>
{% endblock %}

app/templates/subreddit/create.html
{% extends 'base.html' %}

{% block content %}

{% from "_formhelper.html" import render_field %}

<h3>Create Community</h3>

    <form method="POST" action="">

        {{ form.csrf_token }}
        {{ render_field(form.name, class="form-control", placeholder="Community Name") }}
        {{ render_field(form.description, class="form-control", placeholder="Description") }}
        <br>
        <input type="submit" value="Create" class="btn btn-primary">

    </form>
</div>
{% endblock %}

app/templates/subreddit/subreddit.html
{% extends 'base.html' %}

{% block content %}

<h3> Welcome to r/{{subreddit.name}} created by {{subreddit.creator.username}}</h3>
<p>{{ subreddit.description}}</p>

<hr>
{% from "_formhelper.html" import render_field %}

<h4>Create Post</h4>

    <form method="POST" action="">
        {{ form.csrf_token }}
        {{ render_field(form.post_text, class="form-control", placeholder="Whats on your mind ?") }}
        <br>
        <input type="submit" value="Create" class="btn btn-primary">

    </form>


<h4>Posts</h4>
    <div>
    
    {% for post in posts %}
    <h6>post by {{ post.author.username }} on {{ post.timestamp }}</h6>
        {{ post.text }}
        <hr>
    {% endfor %}

    </div>

</ul>

{% endblock %}